spring.application.name=asha-backend

# =========================
# Database Configuration
# =========================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# =========================
# SQL Initialization
# =========================
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Jackson
# =========================
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# =========================
# Server
# =========================
server.port=${PORT:8080}

# =========================
# AWS Bedrock
# =========================
bedrock.model-id=google.gemma-3-4b-it
bedrock.region=ap-south-1
