spring.application.name=asha-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD}}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

server.port=${PORT:8080}

bedrock.model-id=google.gemma-3-4b-it
bedrock.region=ap-south-1
